version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost
      - VITE_USER_SERVICE_URL=http://localhost:7073
      - VITE_COURSE_SERVICE_URL=http://localhost:7071
      - VITE_PAYMENT_SERVICE_URL=http://localhost:7072
      - VITE_VISUALIZATION_SERVICE_URL=http://localhost:3005
  user-managment:
    build:
      context: ./user-managment
      dockerfile: Dockerfile
    ports:
      - "7073:7073" 
    environment:
      PORT: 7073
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      VISUALIZATION_SERVICE_URL: http://visualization-service:3005
    volumes:
      - shared-data:/shared

  course-management:
    build:
      context: ./course-management
      dockerfile: Dockerfile
    ports:
      - "7071:7071"  
    environment:
      PORT: 7071
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      VISUALIZATION_SERVICE_URL: http://visualization-service:3005
    volumes:
      - shared-data:/shared

  payment-management:
    build:
      context: ./payment-management
      dockerfile: Dockerfile
    ports:
      - "7072:7072"  
    environment:
      PORT: 7072
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PAYMENT_BYPASS: ${PAYMENT_BYPASS}
      PAYMENT_BYPASS_AMOUNT: ${PAYMENT_BYPASS_AMOUNT}
      TEST_CARD_NUMBER: ${TEST_CARD_NUMBER}
      VISUALIZATION_SERVICE_URL: http://visualization-service:3005
    volumes:
      - shared-data:/shared

  visualization-service:
    build:
      context: ./visualization-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - VISUALIZATION_PORT=3005

volumes:
  shared-data:
